# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ os }}
    strategy:
      os: ['ubuntu-latest', 'macos-latest']
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
        condarc-file: .condarc.yml
        activate-environment: test
        python-version: 3.6
    # Runs a single command using the runners shell
    - name: Set up test environment
      shell: bash -l {0}
      run: |
        conda install --file requirements.txt
        pip install .
    - name: Check install
      shell: bash -l {0}
      run: |
        synta --version
        synta --help
    - name: launch synta
      shell: bash -l {0}
      run: synta --fna test/GCF_000026905.1_ASM2690v1_genomic.fna.gz --output test/outdir --format gff,gbff,faa,fna,ffn --compress
